/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/table.glb --transform 
Files: public/models/table.glb [113.59KB] > C:\Users\fenfe\Documents\Taylors BCS Programme\Sem 5\Capstone Project II\Inhalo360\inhalo-360\table-transformed.glb [4.88KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/table-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials.base} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.mesh_0_1.geometry} material={materials.handle} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/table-transformed.glb')
